version: "3"

services:
  homaitech_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homaitech_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_HOSTNAME: db
      MONGO_PORT: $MONGO_PORT
      MONGO_DB: $MONGO_DB
      VIRTUAL_HOST: api.homaitech.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: api.homaitech.com
      LETSENCRYPT_EMAIL: lequochungcdt@gmail.com
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app/
      - /app/node_modules
    expose:
      - 5000
    command: npm run start

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  node_modules:

networks:
  default:
    external:
      name: nginx-proxy