FROM node:12
# Create app directory
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app
# Install app dependencies
COPY package*.json ./

USER node

RUN npm install
# Copy app source code
COPY --chown=node:node . .
#Expose port and start application
EXPOSE 5000
CMD [ "npm", "run", "dev" ]